# Generated by Django 3.2.7 on 2021-09-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='project_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
