# Generated by Django 3.2.7 on 2021-10-09 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('API', '0003_issues_project_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='contributors',
            options={'verbose_name_plural': 'Contributors'},
        ),
        migrations.AlterModelOptions(
            name='issues',
            options={'verbose_name_plural': 'Issues'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='comments',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de Création'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='author_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='API.issues', verbose_name='Problème'),
        ),
        migrations.AlterField(
            model_name='contributors',
            name='permission',
            field=models.CharField(choices=[('A', 'all'), ('N', 'none')], max_length=10, verbose_name='Permissions'),
        ),
        migrations.AlterField(
            model_name='contributors',
            name='project_id',
            field=models.IntegerField(verbose_name='ID du Projet'),
        ),
        migrations.AlterField(
            model_name='contributors',
            name='user_id',
            field=models.IntegerField(verbose_name='ID Contributeur'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='assignee_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignee_user', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur assigné'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='author_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_author', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='created_time',
            field=models.DateTimeField(verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='desc',
            field=models.CharField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='priority',
            field=models.CharField(max_length=10, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='project_id',
            field=models.IntegerField(verbose_name='Identifiant Projet'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='status',
            field=models.CharField(max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='tag',
            field=models.CharField(max_length=100, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='author_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_id', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Titre'),
        ),
    ]
